# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Master workflow

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml failsafe:integration-test -Pfailsafe

#    - name: Setup GIT
#      run: |
#        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
#        git config user.name "$GITHUB_ACTOR"
#
#    - name: Update Version & Push
#      env:
#        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#      run: |
#        mvn -B release:prepare
#        git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
#
#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#      env:
#        GITHUB_TOKEN: ${{ github.token }}

    - name: Tag/Release on Push Action
      uses: rymndhng/release-on-push-action@v0.10.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        bump_version_scheme: patch




